### ISSUE TITLE
A bug of ensembling attack methods

### ISSUE THREAD

**Issue by allblueJT** [GodXuxilie/PromptAttack#1]
https://github.com/GodXuxilie/PromptAttack/blob/5b96f4d31f3728e1d6d71415adc2d26285dad433/PromptAttack.py#L284
"perturbation_instruction_index" is supposed to be "i" here, I think.

**Comment by luxinyayaya** [comment]
Thanks for pointing out this bug, we fixed it.

**Comment by luxinyayaya** [comment]
Thanks for pointing out this bug, we fixed it.
