### ISSUE TITLE
cannot findtask descriptions

### ISSUE THREAD

**Issue by gkruddl** [GodXuxilie/PromptAttack#4]
I am trying to reproduce some results, and have issues.

"We list the task descriptions used for each task in Anonymous
Github and calculate the average results over all task descriptions to provide a reliable evaluation for each task."

is written in the paper, but I cannot find the specific instructions (task descriptions) that were given for zs, fs setting.

**Comment by luxinyayaya** [comment]
Thank you for reaching out. 

We have stored the task descriptions in the `.pkl` files located in the `info` directory. You can load the `.pkl` files and extract the task descriptions from there.

You can refer to lines 102–106 in the `robustness_eval.py` file for an example of how to load and retrieve the task descriptions:

```python
def get_td(td_index, dataset):
    with open(os.path.join("info", "{}_info.pkl".format(dataset)), "rb") as f:
        td_fsexample_info = pickle.load(f)
    td = td_fsexample_info["td"][td_index]
    return td
```

Additionally, as mentioned in the paper, we used task descriptions following PromptBench. You can also find the task descriptions in the `method_oriented.py` and `task_oriented.py` files here: https://github.com/microsoft/promptbench/tree/main/promptbench/prompts

Let me know if you need further assistance!
