### ISSUE TITLE
The Average Attack Success Rate has been reproduced: 0.0

### ISSUE THREAD

**Issue by Dwade-Sam** [GodXuxilie/PromptAttack#5]
I ran 12 epochs without changing the code. The Average Attack Success Rate of each round's result was 0. Here are the final results: Average Natural Accuracy: 0.933868501529052, Average Robust Accuracy: 0.933868501529052, Average Attack Success Rate: 0.0

**Comment by luxinyayaya** [comment]
I’ve fixed this bug, and you can retest it. Since the queries are stored in the database file, this won’t consume your API again.

**Comment by Dwade-Sam** [comment]
Thank you, the results have been reproduced.Have a nice day！！
